version: "3.6"
services:
    postgres:
        image: postgres
        restart: always
        environment:
            - DATABASE_HOST=127.0.0.1
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=boilerplate

        ports:
            - "5431:5432"

    db:
        image: tianon/true
        restart: "no"
        depends_on:
            - postgres
